### ISSUE TITLE
ExtensionKit.hx:194: [ERROR] Unable to find event class 'open fl.events.Event'

### ISSUE THREAD

**Issue by utibenkei** [bazzisoft-openfl-extensions/nativetext#1]
First, thank you for making wonderful extension. 

I tested "testapps/nativetext" in the android device. 
When inputting a character, the error occurred.

"
I/trace   ( 1897): ExtensionKit.hx:194: [ERROR] Unable to find event class 'open
fl.events.Event'
"

**Comment by bazzisoft** [comment]
@utibenkei: Pleasure, thanks for testing it out!

Based on the output, it seems that you're running and older version of OpenFL (openfl < 2.0). Is that right? If so, do you have the option of updating to a later stable version?

(I think they changed the flash.events namespace to openfl.events in OpenFL 2.0)

**Comment by utibenkei** [comment]
This is the setting that I have tested .

lime: [2.0.0-alpha.5]
openfl: [2.1.3]

**Comment by bazzisoft** [comment]
I just updated my libs to the latest and I can see the problem now.

Unfortunately, I don't see how to fix it in a portable way. The problem is there are typedefs in `openfl/2,1,3/openfl/events/Event.hx` which point to `openfl/2,1,3/openfl/_v2/events/Event.hx`, unless you're running the newer "next" branch.

I'm creating the event classes using reflection, so I need to specify the exact path to the actual class (typedefs won't work). So, code that works in OpenFL 2.1 won't work in any earlier versions :-S

The only way I can think of to get around this might be to avoid using the standard Event.CHANGE and FocusEvent classes and instead use the custom NativeTextFieldEvent for all change/focus events.

What do you think?

**Comment by utibenkei** [comment]
I understood the contents of this problem.
Because I think that it is a very difficult problem, I leave it to you method.
Thank you for a quick answer.

**Comment by bazzisoft** [comment]
Ok I just updated it now to use the custom event classes. Let me know if it works for you now?

(You'll need to pull both `testapps` and `nativetext`)

**Comment by utibenkei** [comment]
Has checked that the problem was corrected. 
Thank you.
